/// Flutter icons CustomRiotIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomRiotIcons
///      fonts:
///       - asset: fonts/CustomRiotIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomRiotIcons {
  CustomRiotIcons._();

  static const _kFontFam = 'CustomRiotIcons';
  static const _kFontPkg = null;

  static const IconData riot = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
